import axios from "axios";
import { api } from "./constants";

// { plant, startDate: 'YYYY-MM-DD', endDate: 'YYYY-MM-DD' }
export const getSubcontractPlanList = async (body) => {
  const response = await axios.post(`${api}/SubcontractPlan/list`, body);
  return response.data;
};

// Active Material Master records of a plant: { materials: [{ part_number, material_type }] }
export const getSubcontractMaterialLookup = async (body) => {
  const response = await axios.post(`${api}/SubcontractPlan/lookup`, body);
  return response.data;
};

// Manual Fetch — runs the same import the every-4-hours cron runs.
export const fetchSubcontractPlan = async (userId) => {
  const response = await axios.post(`${api}/SubcontractPlan/fetch`, { userId });
  return response.data;
};

// The .xlsx is generated by the backend; returns the file as a Blob.
export const downloadSubcontractPlanExcel = async (body) => {
  const response = await axios.post(`${api}/SubcontractPlan/download`, body, { responseType: "blob" });
  return response.data;
};
