import React, { useEffect, useState } from "react";
import {
  Button, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, TextField,
} from "@mui/material";
import FileDownloadOutlinedIcon from "@mui/icons-material/FileDownloadOutlined";

// Shared "Start Date | End Date | Cancel | Download" popup used by the
// Production Actual and Subcontract Daily Plan screens. It only collects and
// validates the range; the caller's onDownload(startDate, endDate) does the
// actual request (the Excel file is generated by the backend).
const fieldSx = {
  "& .MuiOutlinedInput-root": { borderRadius: "6px", backgroundColor: "#fafbfc" },
  "& .MuiInputBase-input": { fontSize: 12, padding: "8px 10px" },
  "& .MuiInputLabel-root": { fontSize: 12 },
};

const buttonSx = {
  fontSize: 12, fontWeight: 600, textTransform: "none", borderRadius: "6px", boxShadow: "none", padding: "5px 16px",
};

const DateRangeDownloadDialog = ({ open, onClose, onDownload, defaultStart = "", defaultEnd = "", title = "Download Excel" }) => {
  const [startDate, setStartDate] = useState(defaultStart);
  const [endDate, setEndDate] = useState(defaultEnd);
  const [downloading, setDownloading] = useState(false);

  // Re-seed from the screen's current month each time the popup is opened.
  useEffect(() => {
    if (open) {
      setStartDate(defaultStart);
      setEndDate(defaultEnd);
    }
  }, [open, defaultStart, defaultEnd]);

  const error =
    !startDate || !endDate ? "Please select both Start Date and End Date."
      : startDate > endDate ? "Start Date cannot be after End Date."
        : "";

  const handleDownload = async () => {
    if (error || downloading) return;
    setDownloading(true);
    try {
      await onDownload(startDate, endDate);
      onClose();
    } finally {
      setDownloading(false);
    }
  };

  return (
    <Dialog open={open} onClose={downloading ? undefined : onClose} maxWidth="xs" fullWidth>
      <DialogTitle sx={{ fontSize: 15, fontWeight: 700, color: "#1a2233", pb: 1 }}>{title}</DialogTitle>
      <DialogContent sx={{ pt: "8px !important" }}>
        <div style={{ display: "flex", gap: 12, marginTop: 4 }}>
          <TextField
            type="date"
            size="small"
            label="Start Date"
            value={startDate}
            onChange={(e) => setStartDate(e.target.value)}
            InputLabelProps={{ shrink: true }}
            sx={{ flex: 1, ...fieldSx }}
          />
          <TextField
            type="date"
            size="small"
            label="End Date"
            value={endDate}
            onChange={(e) => setEndDate(e.target.value)}
            InputLabelProps={{ shrink: true }}
            sx={{ flex: 1, ...fieldSx }}
          />
        </div>
        {error && (
          <div style={{ marginTop: 8, fontSize: 11.5, fontWeight: 600, color: "#d32f2f" }}>{error}</div>
        )}
      </DialogContent>
      <DialogActions sx={{ px: 3, pb: 2 }}>
        <Button onClick={onClose} disabled={downloading} sx={{ ...buttonSx, color: "#5b6472" }}>
          Cancel
        </Button>
        <Button
          onClick={handleDownload}
          disabled={Boolean(error) || downloading}
          variant="contained"
          disableElevation
          startIcon={downloading ? <CircularProgress size={14} color="inherit" /> : <FileDownloadOutlinedIcon sx={{ fontSize: 16 }} />}
          sx={{ ...buttonSx, backgroundColor: "#0066FF", "&:hover": { backgroundColor: "#0052cc" } }}
        >
          {downloading ? "Downloading..." : "Download"}
        </Button>
      </DialogActions>
    </Dialog>
  );
};

export default DateRangeDownloadDialog;
